---
title: "1. Research Design"
description: |
  Example code used in class discussion.
author:
  - name: Scott Spencer 
    url: https://ssp3nc3r.github.io
    affiliation: Columbia University
    affiliation_url: https://sps.columbia.edu/faculty/scott-spencer
date: "2021 September 15"
output:
  bookdown::html_document2:
    base_format: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  warning = F,
  error = F,
  message = F)
```

# Slide 15

```{r}
library(tidyverse); library(ggthemes)
theme_set( theme_clean() )

set.seed(1)

# (U.S. Census, 2019)
n_nyc     <- 8336817
n_females <- floor(n_nyc * 0.523)
n_males   <- n_nyc - n_females

# (Rosner, 2013)
height_m <- rnorm(n = n_males,   mean = 178.4, sd = 7.6)
height_f <- rnorm(n = n_females, mean = 164.7, sd = 7.1)

population_nyc <- 
  data.frame(
    height = c(height_m, height_f),
    male   = c(rep(TRUE, n_males), rep(FALSE, n_females))
  )
```

# Slide 21

```{r}
samples <- 
  population_nyc %>% 
  slice_sample(n = 100, replace = FALSE)
```

# Slide 26

```{r}
ggplot(samples) + 
  geom_density(aes(x = height))
```

```{r}
ggplot(samples) + 
  geom_density(aes(x = height, 
                   group = male, 
                   fill = male),
               alpha = 0.5) +
  scale_fill_manual(
    breaks = c(FALSE, TRUE), 
    values = c("lightpink", "dodgerblue")) +
  theme(legend.position = "")
```

# Slide 27

```{r}
samples %>%
  group_by(male) %>%
  summarise(
    x_bar = mean(height), 
    var   = var(height), 
    sd    = sd(height)
  )
```

```{r}
ggplot(samples) + 
  geom_density(aes(x = height, 
                   group = male, 
                   fill = male),
               alpha = 0.5) +
  scale_fill_manual(
    breaks = c(FALSE, TRUE), 
    values = c("lightpink", "dodgerblue")) +
  theme(legend.position = "") +
  geom_vline(data = filter(samples, male == FALSE),
             aes(xintercept = mean(height))) +
  geom_vline(data = filter(samples, male == TRUE),
             aes(xintercept = mean(height)))
```

